cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:service_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:service_id>/', views.cart_remove, name='cart_remove'),
]

main_service/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('repair_service.urls')),
                  path('register/', include('account.urls')),
                  path('cart/', include('cart.urls')),
                  path('order/', include('order.urls')),
                  path('statistics/', include('app_statistics.urls')),
                  path('info/', include('info_service.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from repair_service.models import Service
from .cart import Cart
from .forms import CartAddProductForm
from django.core.exceptions import PermissionDenied


@require_POST
def cart_add(request, service_id):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    service = get_object_or_404(Service, id=service_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(service=service,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, service_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    service = get_object_or_404(Service, id=service_id)
    cart.remove(service)
    return redirect('cart:cart_detail')


def cart_detail(request):
    if not request.user.is_authenticated:
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    for item in cart:
        initial = {
            'quantity': item['quantity'],
            'update': True
        }
        item['update_quantity_form'] = CartAddProductForm(initial=initial)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "repair_service/snippets/base.html" %}
{% load static %}

{% block title %}
    Корзина покупок
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'cart/css/detail.css' %}">
{% endblock %}

{% block content %}
    <h1>Корзина покупок</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>service</th>
            <th>Update quantity</th>
            <th>Remove</th>
            <th>Quantity</th>
            <th>Unit price</th>
            <th>Cost</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with service=item.service %}
                <tr>
                    <td>
                        <div class="service-image">
                            <img src="
                                {% if service.image %}
                                {{ service.image.url }}
                                {% else %}
                                {% static 'cart/img/no_content.png' %}
                                {% endif %}"
                                 alt="Service photo">
                        </div>
                    </td>
                    <td>{{ service.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' service.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Обновить">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a href="{% url 'cart:cart_remove' service.id %}">Delete</a></td>
                    <td>
                        {{ item.quantity }}
                    </td>
                    <td class="num">{{ item.cost }}</td>
                    <td class="num">{{ item.total_cost }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="5"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'service_list' %}" class="button light">To services</a>
        <a href="{% url 'order_create' %}" class="button">
            Checkout
        </a>
    </p>
{% endblock %}