cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:service_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:service_id>/', views.cart_remove, name='cart_remove'),
]

info_service/urls.py
from django.urls import path
from . import views

app_name = 'info_service'

urlpatterns = [
    path('about', views.about_company, name='about_company'),
    path('news', views.news_list, name='news_list'),
    path('news/<int:id>/', views.news_by_id, name='news_detail'),
    path('faq', views.faq_list, name='faq'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('workers', views.our_workers, name='workers'),
    path('sales', views.sales, name='sales'),
    path('vacancies', views.vacancy_list, name='vacancies'),
    path('feedback', views.feedbacks_page, name='feedbacks_page'),
    path('feedback/create/', views.create_feedback, name='create_feedback')
]

main_service/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('repair_service.urls')),
                  path('register/', include('account.urls')),
                  path('cart/', include('cart.urls')),
                  path('order/', include('order.urls')),
                  path('statistics/', include('app_statistics.urls')),
                  path('info/', include('info_service.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info_service/models.py
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models

from account.models import Account
from repair_service.models import Service


class News(models.Model):
    title = models.CharField(max_length=50)
    short_description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='info_service/news',
                              help_text='News image',
                              blank=True,
                              null=True)
    text = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class PromoCode(models.Model):
    code = models.IntegerField(unique=True)
    expiration_date = models.DateField()
    discount = models.SmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)]
    )
    activated = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.code}-{self.expiration_date}'


class Vacancy(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    location = models.CharField(max_length=50)
    posted_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title


class Feedback(models.Model):
    reviewer = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
    )
    used_service = models.ForeignKey(
        Service,
        on_delete=models.CASCADE
    )
    text = models.TextField(max_length=256)
    score = models.SmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.reviewer.email}-{self.score}'


class Worker(models.Model):
    name = models.CharField(max_length=256)
    age = models.SmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(150)])
    job_title = models.CharField(max_length=100)
    phone = models.CharField(
        max_length=20,
        validators=[RegexValidator(r'^\+?1?\d{9,15}$')]
    )
    email = models.EmailField(unique=True)
    image = models.ImageField(
        upload_to='info_service/workers',
        help_text='Worker image',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.name

info_service/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from datetime import date
from info_service.models import News, PromoCode, Vacancy, Feedback, Worker
from repair_service.models import Service


# Create your views here.


def about_company(request):
    return render(request, 'info_service/about.html')


def news_list(request):
    news = News.objects.order_by('-created_at')  # sort by creation time in descending order
    return render(request, 'info_service/news.html', {'news_list': news})


def news_by_id(request, id):
    news = get_object_or_404(News, id=id)
    return render(request, 'info_service/news_detail.html', {'news': news})


def faq_list(request):
    return render(request, 'info_service/faq.html')


def privacy_policy(request):
    return render(request, 'info_service/privacy_policy.html')


def our_workers(request):
    workers = Worker.objects.all()
    return render(request, 'info_service/workers.html', {'workers': workers})


def sales(request):
    current_date = date.today()
    active_codes = PromoCode.objects.filter(
        expiration_date__gte=current_date,
        activated=False
    )
    inactive_codes = PromoCode.objects.filter(
        Q(expiration_date__lt=current_date) | Q(activated=True)
    )

    return render(request, 'info_service/sales.html', {
        'active_codes': active_codes,
        'inactive_codes': inactive_codes
    })


def vacancy_list(request):
    vacancies = Vacancy.objects.all()
    return render(request, 'info_service/vacancies.html', {'vacancies': vacancies})


def feedbacks_page(request):
    feedbacks = Feedback.objects.all()
    available_services = Service.objects.all()
    return render(request, 'info_service/feedback.html', {
        'feedbacks': feedbacks,
        'available_services': available_services
    })


def create_feedback(request):
    if request.method == 'POST':
        request_data = request.POST
        feedback = Feedback(
            reviewer=request.user,
            used_service=Service.objects.filter(name=request_data.get('used_service')).first(),
            text=request_data.get('text'),
            score=int(request_data.get('score'))
        )
        feedback.save()

    return redirect('info_service:feedbacks_page')

info_service/templates/info_service/about.html
{% extends 'repair_service/snippets/base.html' %}

{% load static %}

{% block content %}
    <header>
        <h1>About "Repair Center"</h1>
    </header>
    <div id="company-info">
        <h2>About Our Company:</h2>
        <p><strong>History:</strong></p>
        <ul>
            <li>2005: The company was founded as a small workshop for repairing mobile devices.</li>
            <li>2010: We expanded our range of services to include laptops and computers repair.</li>
            <li>2015: Opening of a new branch in a different city.</li>
            <li>2020: We became official partners of major electronics manufacturers.</li>
        </ul>
        <div class="certificate">
            <div class="header">
                <h2>Repair Service Certificate</h2>
            </div>
            <div class="customer-info">
                <p><strong>Certificate Number:</strong> 123456</p>
                <p><strong>Date of Service:</strong> September 20, 2023</p>
                <p><strong>Customer Name:</strong> John Doe</p>
                <p><strong>Customer Contact Information:</strong> john.doe@example.com</p>
            </div>
            <div class="item-info">
                <p><strong>Description of Repaired Item:</strong></p>
                <ul>
                    <li><strong>Product Name:</strong> Laptop</li>
                    <li><strong>Brand:</strong> Dell</li>
                    <li><strong>Model:</strong> Inspiron 15</li>
                    <li><strong>Serial Number:</strong> ABC123456</li>
                </ul>
            </div>
            <div class="repair-info">
                <p><strong>Description of Repair Work:</strong></p>
                <ul>
                    <li><strong>Issue/Problem:</strong> Screen replacement</li>
                    <li><strong>Repair/Service Performed:</strong> Replaced the laptop screen with a new one.</li>
                    <li><strong>Replacement Parts (if any):</strong> LCD screen</li>
                </ul>
            </div>
            <div class="technician-info">
                <p><strong>Repair Technician:</strong></p>
                <p><strong>Technician Name:</strong> Jane Smith</p>
                <p><strong>Technician Contact Information:</strong> jane.smith@example.com</p>
            </div>
            <div class="charges">
                <p><strong>Service Charges:</strong></p>
                <p><strong>Total Service Cost:</strong> $150.00</p>
                <p><strong>Payment Method:</strong> Credit Card</p>
            </div>
            <div class="warranty">
                <p><strong>Warranty Information:</strong></p>
                <p><strong>Warranty Period:</strong> 90 days</p>
                <p><strong>Terms and Conditions:</strong> This warranty covers the replaced screen for 90 days from the
                    date of service.</p>
            </div>
            <div class="customer-signature">
                <p>Customer Signature: __________________________</p>
            </div>
            <p>Thank you for choosing our repair service. If you have any questions or concerns, please don't hesitate
                to contact us.</p>
            <div class="footer">
                <p><strong>Company Name:</strong> ABC Repair Services</p>
                <p><strong>Company Address:</strong> 123 Main Street, Cityville</p>
                <p><strong>Company Phone Number:</strong> (555) 123-4567</p>
                <p><strong>Company Website:</strong> www.abcrepair.com</p>
            </div>
        </div>
        <p><strong>Contact Information:</strong></p>
        <ul>
            <li>Company Name: Repair Center</li>
            <li>Legal Address: 123 Example Street, City</li>
            <li>Phone: +7 (123) 456-7890</li>
            <li>Email: info@repaircenter.com</li>
            <li>OGRN (Primary State Registration Number): 1234567890</li>
            <li>TIN (Taxpayer Identification Number): 0987654321</li>
            <li>Bank Account: 98765432109876543210 at Reliable Bank</li>
        </ul>
    </div>
    <div id="video">
        <h2>Video:</h2>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/tgbNymZ7vqY"
                allowfullscreen>
        </iframe>
    </div>
    <div id="logo">
        <h2>Logo:</h2>
        <img src="{% static 'info_service/img/repair_center_logo.jpg' %}" alt="Logo of 'Repair Center'" title="logo"
             style="max-height: 300px">
    </div>
    <hr>
    <p>We strive to be the best in our field, providing high-quality services at reasonable prices. Thank you for
        choosing us - your device is in safe hands with "Repair Center".</p>
    <a href="{% static 'info_service/file_to_download.txt' %}" download>DOWNLOAD DOCUMENT HERE</a>
{% endblock %}

info_service/templates/info_service/faq.html
{% extends 'repair_service/snippets/base.html' %}

{% block title %}FAQ{% endblock %}

{% block content %}
    <header>
        <h1>Repair Service Center FAQ</h1>
    </header>

    <blockquote>
        <p>Spring has come, flowers bloom,<br>
            Fields turn green, sky is clear.</p>

        <p>Birds are singing, the wind whispers to the branches,<br>
            Nature's time, so beautiful, lies ahead.</p>
    </blockquote>

    <main>
        <p><dfn>FAQ</dfn> - stands for "Frequently Asked Questions."</p>
        <details>
            <summary>What types of devices do you repair?</summary>
            <p>We repair a wide range of devices, including smartphones, laptops, tablets, and more. Feel free to
                contact us with specific inquiries.</p>
        </details>

        <details>
            <summary>How long does a typical repair take?</summary>
            <p>The repair time can vary depending on the type and extent of the damage. We strive to complete most
                repairs within 24-48 hours.</p>
        </details>

        <details>
            <summary>How much will my repair cost?</summary>
            <p>The cost of repair depends on the device and the extent of the damage. We provide free estimates, so
                bring your device in for an assessment.</p>
        </details>

        <details>
            <summary>What payment methods do you accept?</summary>
            <p>We accept cash, credit cards, and mobile payment apps for your convenience.</p>
        </details>

        <details>
            <summary>Do you offer warranties on your repairs?</summary>
            <p>Yes, we provide a limited warranty on our repair services. Please ask for details when you bring in your
                device.</p>
        </details>

        <details>
            <summary>What if I'm not satisfied with the repair?</summary>
            <p>We aim for customer satisfaction. If you encounter any issues after a repair, please contact us, and we
                will address it promptly.</p>
        </details>
    </main>
{% endblock %}

info_service/templates/info_service/feedback.html
{% extends 'repair_service/snippets/base.html' %}

{% load static %}

{% block title %}Feedback{% endblock %}

{% block content %}
    <h1>Existing feedbacks</h1>
    {% for feedback in feedbacks %}
        <p><b>Author: </b>{{ feedback.reviewer.username }}</p>
        <p><b>Used service: </b>{{ feedback.used_service.name }}</p>
        <pre>{{ feedback.text }}</pre>
        <p><b>Score: </b>{{ feedback.score }}/10⭐</p>
        <p>Date: {{ feedback.created_at }}</p>
    {% endfor %}

    <h1>Send Your Feedback!</h1>
    {% if request.user.is_authenticated %}
        <h2>Just fill few lines</h2>
        <form method="post" action="{% url 'info_service:create_feedback' %}">
            {% csrf_token %}
            <label>
                Used Service:
                <select id="used_service" name="used_service" required>
                    {% for service in available_services %}
                        <option>{{ service.name }}</option>
                    {% endfor %}
                </select>
            </label>
            <br><br>
            <label>
                Feedback Text:
                <textarea id="id_text" name="text" maxlength="256" required></textarea>
            </label>
            <br><br>
            <label>
                Score (0-10):
                <input type="number" id="id_score" name="score" min="0" max="10" required>
            </label>
            <br><br>
            <button type="submit">Submit Feedback</button>
        </form>
    {% else %}
        <p>To be able to leave your review authenticate firstly</p>
    {% endif %}

{% endblock %}

info_service/templates/info_service/news.html
{% extends 'repair_service/snippets/base.html' %}

{% load static %}

{% block title %}News{% endblock %}

{% block content %}
    <h1>Actual news</h1>
    {% for news in news_list %}
        <article>
            <h2>{{ news.title }}</h2>
            <p>{{ news.created_at }}</p>
            <p>{{ news.short_description }}</p>>
            <a href="/info/news/{{ news.id }}">
                <img src="{{ news.image.url }}" alt="Click to see full news"/>
                <br>
                Read more...
            </a>
        </article>
    {% endfor %}
{% endblock %}

info_service/templates/info_service/news_detail.html
{% extends 'repair_service/snippets/base.html' %}

{% block title %}{{ news.title }}{% endblock %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
    <article>
        <h1>{{ news.title }}</h1>
        <p>{{ news.created_at }}</p>
        <h2>{{ news.short_description }}</h2>
        <img src="{{ news.image.url }}" alt="News image" style="max-height: 400px"/>
        <pre>{{ news.text|safe }}</pre>
    </article>
{% endblock %}

info_service/templates/info_service/privacy_policy.html
{% extends 'repair_service/snippets/base.html' %}

{% load static %}

{% block title %}Privacy policy{% endblock %}

{% block content %}
    <header>
        <h1>Privacy Policy</h1>
    </header>
    <main>
        <p>Last Updated:
            <time datetime="2023-09-11T14:30:00Z">11th september 2023, 14:30 UTC</time>
        </p>

        <p>Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your personal
            information.</p>

        <h2>Information We Collect</h2>

        <p>We collect the following types of information:</p>

        <ul>
            <li><strong>Name and Contact Information:</strong> We may collect your name, email address, phone number,
                and
                address for communication and service purposes.
            </li>
            <li><strong>Device Information:</strong> We may collect information about your device, including your IP
                address, browser, operating system, and version.
            </li>
        </ul>

        <h2>How We Use Information</h2>

        <p>We use the collected information for the following purposes:</p>

        <ul>
            <li>
                <strong>Service Delivery:</strong> We use your data to process repair orders and provide related
                services.
            </li>
            <li><strong>Communication:</strong> We may contact you regarding your orders or inquiries.</li>
            <li><strong>Website Improvement:</strong> We analyze device and website usage data to enhance our website's
                functionality and optimize your experience.
            </li>
        </ul>

        <h2>Data Protection</h2>

        <p>We take security measures to protect your data from unauthorized access, loss, or disclosure. Your data is
            stored
            on secure servers, and access is restricted to authorized personnel.</p>

        <h2>Sharing Information with Third Parties</h2>

        <p>We do not sell, exchange, or share your personal information with third parties unless required for
            fulfilling
            our obligations or by law.</p>

        <h2>Changes to this Privacy Policy</h2>

        <p>We may update this Privacy Policy from time to time. Any changes will be posted on this page, along with the
            "Last Updated" date.</p>

        <h2>Your Rights</h2>

        <p>You have the right to access your personal data and may request corrections, deletions, or restrictions on
            processing. If you have any questions or requests regarding your personal information, please contact us
            using
            the information below.</p>

        <h2>Contact Information</h2>

        <p>If you have any questions or suggestions regarding our Privacy Policy, please contact us at:</p>

        <p>Repair Service<br>
            Gikalo 9<br>
            +375445556677<br>
            rep.service@gmail.com
        </p>
    </main>
{% endblock %}

info_service/templates/info_service/sales.html
{% extends 'repair_service/snippets/base.html' %}

{% load static %}

{% block title %}Sales{% endblock %}

{% block content %}
    {% if active_codes.count == 0 %}
        <h1>There are no avaiable codes😢</h1>
    {% else %}
        <section>
            <h1>Available promocodes</h1>
            {% for promocode in active_codes %}
                <div class="promo-code">
                    <hr>
                    <p><b>Code </b> {{ promocode.code }}</p>
                    <p><b>Discount</b> {{ promocode.discount }}</p>
                    <p><b>Expiration date</b> {{ promocode.expiration_date }}</p>
                </div>
            {% endfor %}
        </section>
    {% endif %}
    <section>
        <h1>Archived promocodes</h1>
        {% for promocode in active_codes %}
            <div class="promo-code">
                <hr>
                <p><b>Code </b> {{ promocode.code }}</p>
                <p><b>Discount</b> {{ promocode.discount }}</p>
                <p><b>Expiration date</b> {{ promocode.expiration_date }}</p>
            </div>
        {% endfor %}
    </section>
{% endblock %}

info_service/templates/info_service/vacancies.html
{% extends 'repair_service/snippets/base.html' %}

{% load static %}

{% block title %}Vacancies{% endblock %}

{% block content %}
    <h1 id="vacancy_header">Vacancies in Repair Center</h1>
    <ul>
        {% for vacancy in vacancies %}
            <li>
                <h2>{{ vacancy.title }}</h2>
                <span>Description:</span>
                <pre>{{ vacancy.description }}</pre>
                <p>Location: {{ vacancy.location }}</p>
                <p>Posted Date: {{ vacancy.posted_date }}</p>
            </li>
        {% endfor %}
    </ul>
    <a href="#vacancy_header">Go to beginning</a>
{% endblock %}

info_service/templates/info_service/workers.html
{% extends 'repair_service/snippets/base.html' %}

{% load static %}

{% block title %}Our workers{% endblock %}

{% block content %}
    <header>
        <h1>Repair Service Center Workers</h1>
    </header>
    {% for worker in workers %}
        <div itemscope itemtype="https://schema.org/Person">
            <span itemprop="name"><strong>{{ worker.name }}</strong></span><br>
            <span itemprop="jobTitle"><b>Job title: </b>{{ worker.job_title }}</span><br>
            <span itemprop="age"><b>Age: </b>{{ worker.age }}</span><br>
            <b>Email: </b><a itemprop="email" href="mailto:{{ worker.email }}">{{ worker.email }}</a><br>
            <b>Phone: </b><a itemprop="telephone" href="tel:{{ worker.phone }}">{{ worker.phone }}</a><br>
            <img itemprop="image" src="{{ worker.image.url }}" alt="{{ worker.name }}"/><br>
        </div>
    {% endfor %}

    <div class="contact-info">
        <h2>Contact Information</h2>
        <p>If you have any questions or need our repair services, feel free to reach out to any of our team members
            listed
            above.</p>
        <p>Address: Gikalo 9, Minsk, Belarus</p>
    </div>
{% endblock %}